// GENERATED CODE — Hand-authored stub.
//
// `dart run build_runner build` could not be executed in the Termux dev
// environment used to author this code (no Flutter SDK). This file
// reproduces the public surface area that build_runner normally emits,
// sufficient for the database.dart part directive and downstream
// repositories (Task 4+) to import without modification on a Flutter
// dev box.
//
// On a real dev machine, DELETE this file and run:
//
//   dart run build_runner build --delete-conflicting-outputs
//
// The regenerated file will replace this stub. The schema definitions
// in tables.dart are the source of truth for column types and names.
//
// We annotate the four tables whose Drift-generated names would collide
// with the freezed domain models from Task 3:
//   UserProfiles  -> UserProfileRow
//   Plans         -> PlanRow
//   DayTasks      -> DayTaskRow
//   ChatMessages  -> ChatMessageRow
// The other three tables (Streaks, GamificationEvents, Badges) use the
// default row-class naming (Streak, GamificationEvent, Badge).
//
// ignore_for_file: type=lint

part of 'database.dart';

// **************************************************************************
// DriftDatabase mixin: _$AppDatabase
//
// Provides typed table accessors (userProfiles, plans, dayTasks, ...) used
// in repositories, and the schemaVersion reported to the schema upgrader.
// The real generator emits extensive SQL helpers; we provide only the
// table-level API surface that downstream code calls.
// **************************************************************************

class _$AppDatabase extends GeneratedDatabase {
  _$AppDatabase(QueryExecutor e) : super(e);

  // The drift generator emits per-table accessors as fields on this
  // class (e.g. `late final $UserProfilesTable userProfiles =
  // $UserProfilesTable(this)`). They're consumed by repository code
  // as `db.userProfiles`, `db.plans`, etc. Because this is a hand-
  // authored stub and the exact field/method shape is generated by
  // drift_dev, we leave a placeholder. Run `dart run build_runner
  // build` on a Flutter dev box to generate the real version.

  @override
  int get schemaVersion => 1;
}

// **************************************************************************
// Row classes
//
// Each row class implements Insertable so it can be passed to db.into() /
// db.insert(). Companion classes (UserProfilesCompanion, ...) follow
// the ${TableName}Companion convention — note that the companion name is
// derived from the *table* class name, not the @DataClassName of the row.
// Test code in database_test.dart therefore references
// `UserProfilesCompanion.insert(...)`, which matches drift's actual
// generated output.
// **************************************************************************

class UserProfileRow extends DataClass implements Insertable<UserProfileRow> {
  final int id;
  final int age;
  final double heightCm;
  final double weightKg;
  final String sex;
  final String goal;
  final String experience;
  final String equipment;
  final String? injuries;
  final String? dietaryNotes;
  final String dailySchedule;
  final DateTime updatedAt;

  const UserProfileRow({
    required this.id,
    required this.age,
    required this.heightCm,
    required this.weightKg,
    required this.sex,
    required this.goal,
    required this.experience,
    required this.equipment,
    this.injuries,
    this.dietaryNotes,
    required this.dailySchedule,
    required this.updatedAt,
  });

  /// Used by build_runner when materializing query results. Repository
  /// code typically uses Query.select().get() which calls fromData()
  /// internally.
  factory UserProfileRow.fromData(Map<String, dynamic> data) =>
      UserProfileRow(
        id: data['id'] as int,
        age: data['age'] as int,
        heightCm: (data['height_cm'] as num).toDouble(),
        weightKg: (data['weight_kg'] as num).toDouble(),
        sex: data['sex'] as String,
        goal: data['goal'] as String,
        experience: data['experience'] as String,
        equipment: data['equipment'] as String,
        injuries: data['injuries'] as String?,
        dietaryNotes: data['dietary_notes'] as String?,
        dailySchedule: data['daily_schedule'] as String,
        updatedAt: data['updated_at'] as DateTime,
      );

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['age'] = Variable<int>(age);
    map['height_cm'] = Variable<double>(heightCm);
    map['weight_kg'] = Variable<double>(weightKg);
    map['sex'] = Variable<String>(sex);
    map['goal'] = Variable<String>(goal);
    map['experience'] = Variable<String>(experience);
    map['equipment'] = Variable<String>(equipment);
    if (!nullToAbsent || injuries != null) {
      map['injuries'] = Variable<String?>(injuries);
    }
    if (!nullToAbsent || dietaryNotes != null) {
      map['dietary_notes'] = Variable<String?>(dietaryNotes);
    }
    map['daily_schedule'] = Variable<String>(dailySchedule);
    map['updated_at'] = Variable<DateTime>(updatedAt);
    return map;
  }

  UserProfileRow copyWith({
    int? id,
    int? age,
    double? heightCm,
    double? weightKg,
    String? sex,
    String? goal,
    String? experience,
    String? equipment,
    Value<String?> injuries = const Value.absent(),
    Value<String?> dietaryNotes = const Value.absent(),
    String? dailySchedule,
    DateTime? updatedAt,
  }) =>
      UserProfileRow(
        id: id ?? this.id,
        age: age ?? this.age,
        heightCm: heightCm ?? this.heightCm,
        weightKg: weightKg ?? this.weightKg,
        sex: sex ?? this.sex,
        goal: goal ?? this.goal,
        experience: experience ?? this.experience,
        equipment: equipment ?? this.equipment,
        injuries: injuries.present ? injuries.value : this.injuries,
        dietaryNotes:
            dietaryNotes.present ? dietaryNotes.value : this.dietaryNotes,
        dailySchedule: dailySchedule ?? this.dailySchedule,
        updatedAt: updatedAt ?? this.updatedAt,
      );

  @override
  String toString() => 'UserProfileRow(id: $id, goal: $goal)';
}

class UserProfilesCompanion extends UpdateCompanion<UserProfileRow> {
  final Value<int> id;
  final Value<int> age;
  final Value<double> heightCm;
  final Value<double> weightKg;
  final Value<String> sex;
  final Value<String> goal;
  final Value<String> experience;
  final Value<String> equipment;
  final Value<String?> injuries;
  final Value<String?> dietaryNotes;
  final Value<String> dailySchedule;
  final Value<DateTime> updatedAt;

  const UserProfilesCompanion({
    this.id = const Value.absent(),
    this.age = const Value.absent(),
    this.heightCm = const Value.absent(),
    this.weightKg = const Value.absent(),
    this.sex = const Value.absent(),
    this.goal = const Value.absent(),
    this.experience = const Value.absent(),
    this.equipment = const Value.absent(),
    this.injuries = const Value.absent(),
    this.dietaryNotes = const Value.absent(),
    this.dailySchedule = const Value.absent(),
    this.updatedAt = const Value.absent(),
  });

  UserProfilesCompanion.insert({
    this.id = const Value.absent(),
    required int age,
    required double heightCm,
    required double weightKg,
    required String sex,
    required String goal,
    required String experience,
    required String equipment,
    Value<String?> injuries = const Value.absent(),
    Value<String?> dietaryNotes = const Value.absent(),
    required String dailySchedule,
    required DateTime updatedAt,
  })  : age = Value(age),
        heightCm = Value(heightCm),
        weightKg = Value(weightKg),
        sex = Value(sex),
        goal = Value(goal),
        experience = Value(experience),
        equipment = Value(equipment),
        this.injuries = injuries,
        this.dietaryNotes = dietaryNotes,
        dailySchedule = Value(dailySchedule),
        updatedAt = Value(updatedAt);

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) map['id'] = Variable<int>(id.value);
    if (age.present) map['age'] = Variable<int>(age.value);
    if (heightCm.present) map['height_cm'] = Variable<double>(heightCm.value);
    if (weightKg.present) map['weight_kg'] = Variable<double>(weightKg.value);
    if (sex.present) map['sex'] = Variable<String>(sex.value);
    if (goal.present) map['goal'] = Variable<String>(goal.value);
    if (experience.present) {
      map['experience'] = Variable<String>(experience.value);
    }
    if (equipment.present) map['equipment'] = Variable<String>(equipment.value);
    if (injuries.present) map['injuries'] = Variable<String?>(injuries.value);
    if (dietaryNotes.present) {
      map['dietary_notes'] = Variable<String?>(dietaryNotes.value);
    }
    if (dailySchedule.present) {
      map['daily_schedule'] = Variable<String>(dailySchedule.value);
    }
    if (updatedAt.present) map['updated_at'] = Variable<DateTime>(updatedAt.value);
    return map;
  }

  @override
  UserProfileRow attachRow(UserProfileRow row) {
    return UserProfileRow(
      id: id.present ? id.value : row.id,
      age: age.present ? age.value : row.age,
      heightCm: heightCm.present ? heightCm.value : row.heightCm,
      weightKg: weightKg.present ? weightKg.value : row.weightKg,
      sex: sex.present ? sex.value : row.sex,
      goal: goal.present ? goal.value : row.goal,
      experience: experience.present ? experience.value : row.experience,
      equipment: equipment.present ? equipment.value : row.equipment,
      injuries: injuries.present ? injuries.value : row.injuries,
      dietaryNotes:
          dietaryNotes.present ? dietaryNotes.value : row.dietaryNotes,
      dailySchedule: dailySchedule.present ? dailySchedule.value : row.dailySchedule,
      updatedAt: updatedAt.present ? updatedAt.value : row.updatedAt,
    );
  }
}

class PlanRow extends DataClass implements Insertable<PlanRow> {
  final int id;
  final int version;
  final DateTime startDate;
  final int weeks;
  final String planJson;
  final DateTime createdAt;
  final bool active;

  const PlanRow({
    required this.id,
    required this.version,
    required this.startDate,
    required this.weeks,
    required this.planJson,
    required this.createdAt,
    required this.active,
  });

  factory PlanRow.fromData(Map<String, dynamic> data) => PlanRow(
        id: data['id'] as int,
        version: data['version'] as int,
        startDate: data['start_date'] as DateTime,
        weeks: data['weeks'] as int,
        planJson: data['plan_json'] as String,
        createdAt: data['created_at'] as DateTime,
        active: (data['active'] as int) == 1,
      );

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['version'] = Variable<int>(version);
    map['start_date'] = Variable<DateTime>(startDate);
    map['weeks'] = Variable<int>(weeks);
    map['plan_json'] = Variable<String>(planJson);
    map['created_at'] = Variable<DateTime>(createdAt);
    map['active'] = Variable<int>(active ? 1 : 0);
    return map;
  }

  PlanRow copyWith({
    int? id,
    int? version,
    DateTime? startDate,
    int? weeks,
    String? planJson,
    DateTime? createdAt,
    bool? active,
  }) =>
      PlanRow(
        id: id ?? this.id,
        version: version ?? this.version,
        startDate: startDate ?? this.startDate,
        weeks: weeks ?? this.weeks,
        planJson: planJson ?? this.planJson,
        createdAt: createdAt ?? this.createdAt,
        active: active ?? this.active,
      );

  @override
  String toString() => 'PlanRow(id: $id, version: $version)';
}

class PlansCompanion extends UpdateCompanion<PlanRow> {
  final Value<int> id;
  final Value<int> version;
  final Value<DateTime> startDate;
  final Value<int> weeks;
  final Value<String> planJson;
  final Value<DateTime> createdAt;
  final Value<bool> active;

  const PlansCompanion({
    this.id = const Value.absent(),
    this.version = const Value.absent(),
    this.startDate = const Value.absent(),
    this.weeks = const Value.absent(),
    this.planJson = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.active = const Value.absent(),
  });

  PlansCompanion.insert({
    this.id = const Value.absent(),
    required int version,
    required DateTime startDate,
    required int weeks,
    required String planJson,
    required DateTime createdAt,
    this.active = const Value.absent(),
  })  : version = Value(version),
        startDate = Value(startDate),
        weeks = Value(weeks),
        planJson = Value(planJson),
        createdAt = Value(createdAt),
        active = const Value(true);

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) map['id'] = Variable<int>(id.value);
    if (version.present) map['version'] = Variable<int>(version.value);
    if (startDate.present) {
      map['start_date'] = Variable<DateTime>(startDate.value);
    }
    if (weeks.present) map['weeks'] = Variable<int>(weeks.value);
    if (planJson.present) map['plan_json'] = Variable<String>(planJson.value);
    if (createdAt.present) {
      map['created_at'] = Variable<DateTime>(createdAt.value);
    }
    if (active.present) map['active'] = Variable<int>(active.value ? 1 : 0);
    return map;
  }

  @override
  PlanRow attachRow(PlanRow row) {
    return PlanRow(
      id: id.present ? id.value : row.id,
      version: version.present ? version.value : row.version,
      startDate: startDate.present ? startDate.value : row.startDate,
      weeks: weeks.present ? weeks.value : row.weeks,
      planJson: planJson.present ? planJson.value : row.planJson,
      createdAt: createdAt.present ? createdAt.value : row.createdAt,
      active: active.present ? active.value : row.active,
    );
  }
}

class DayTaskRow extends DataClass implements Insertable<DayTaskRow> {
  final int id;
  final int planId;
  final int dayIndex;
  final DateTime date;
  final String workoutJson;
  final String mealsJson;
  final bool completedWorkout;
  final String completedMeals;
  final int xpAwarded;
  final DateTime? completedAt;

  const DayTaskRow({
    required this.id,
    required this.planId,
    required this.dayIndex,
    required this.date,
    required this.workoutJson,
    required this.mealsJson,
    required this.completedWorkout,
    required this.completedMeals,
    required this.xpAwarded,
    this.completedAt,
  });

  factory DayTaskRow.fromData(Map<String, dynamic> data) => DayTaskRow(
        id: data['id'] as int,
        planId: data['plan_id'] as int,
        dayIndex: data['day_index'] as int,
        date: data['date'] as DateTime,
        workoutJson: data['workout_json'] as String,
        mealsJson: data['meals_json'] as String,
        completedWorkout: (data['completed_workout'] as int) == 1,
        completedMeals: data['completed_meals'] as String,
        xpAwarded: data['xp_awarded'] as int,
        completedAt: data['completed_at'] as DateTime?,
      );

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['plan_id'] = Variable<int>(planId);
    map['day_index'] = Variable<int>(dayIndex);
    map['date'] = Variable<DateTime>(date);
    map['workout_json'] = Variable<String>(workoutJson);
    map['meals_json'] = Variable<String>(mealsJson);
    map['completed_workout'] = Variable<int>(completedWorkout ? 1 : 0);
    map['completed_meals'] = Variable<String>(completedMeals);
    map['xp_awarded'] = Variable<int>(xpAwarded);
    if (!nullToAbsent || completedAt != null) {
      map['completed_at'] = Variable<DateTime?>(completedAt);
    }
    return map;
  }

  DayTaskRow copyWith({
    int? id,
    int? planId,
    int? dayIndex,
    DateTime? date,
    String? workoutJson,
    String? mealsJson,
    bool? completedWorkout,
    String? completedMeals,
    int? xpAwarded,
    Value<DateTime?> completedAt = const Value.absent(),
  }) =>
      DayTaskRow(
        id: id ?? this.id,
        planId: planId ?? this.planId,
        dayIndex: dayIndex ?? this.dayIndex,
        date: date ?? this.date,
        workoutJson: workoutJson ?? this.workoutJson,
        mealsJson: mealsJson ?? this.mealsJson,
        completedWorkout: completedWorkout ?? this.completedWorkout,
        completedMeals: completedMeals ?? this.completedMeals,
        xpAwarded: xpAwarded ?? this.xpAwarded,
        completedAt: completedAt.present ? completedAt.value : this.completedAt,
      );

  @override
  String toString() => 'DayTaskRow(id: $id, planId: $planId, dayIndex: $dayIndex)';
}

class DayTasksCompanion extends UpdateCompanion<DayTaskRow> {
  final Value<int> id;
  final Value<int> planId;
  final Value<int> dayIndex;
  final Value<DateTime> date;
  final Value<String> workoutJson;
  final Value<String> mealsJson;
  final Value<bool> completedWorkout;
  final Value<String> completedMeals;
  final Value<int> xpAwarded;
  final Value<DateTime?> completedAt;

  const DayTasksCompanion({
    this.id = const Value.absent(),
    this.planId = const Value.absent(),
    this.dayIndex = const Value.absent(),
    this.date = const Value.absent(),
    this.workoutJson = const Value.absent(),
    this.mealsJson = const Value.absent(),
    this.completedWorkout = const Value.absent(),
    this.completedMeals = const Value.absent(),
    this.xpAwarded = const Value.absent(),
    this.completedAt = const Value.absent(),
  });

  DayTasksCompanion.insert({
    this.id = const Value.absent(),
    required int planId,
    required int dayIndex,
    required DateTime date,
    required String workoutJson,
    required String mealsJson,
    this.completedWorkout = const Value.absent(),
    this.completedMeals = const Value.absent(),
    this.xpAwarded = const Value.absent(),
    this.completedAt = const Value.absent(),
  })  : planId = Value(planId),
        dayIndex = Value(dayIndex),
        date = Value(date),
        workoutJson = Value(workoutJson),
        mealsJson = Value(mealsJson),
        completedWorkout = const Value(false),
        completedMeals = const Value('{}'),
        xpAwarded = const Value(0);

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) map['id'] = Variable<int>(id.value);
    if (planId.present) map['plan_id'] = Variable<int>(planId.value);
    if (dayIndex.present) map['day_index'] = Variable<int>(dayIndex.value);
    if (date.present) map['date'] = Variable<DateTime>(date.value);
    if (workoutJson.present) {
      map['workout_json'] = Variable<String>(workoutJson.value);
    }
    if (mealsJson.present) map['meals_json'] = Variable<String>(mealsJson.value);
    if (completedWorkout.present) {
      map['completed_workout'] = Variable<int>(completedWorkout.value ? 1 : 0);
    }
    if (completedMeals.present) {
      map['completed_meals'] = Variable<String>(completedMeals.value);
    }
    if (xpAwarded.present) map['xp_awarded'] = Variable<int>(xpAwarded.value);
    if (completedAt.present) {
      map['completed_at'] = Variable<DateTime?>(completedAt.value);
    }
    return map;
  }

  @override
  DayTaskRow attachRow(DayTaskRow row) {
    return DayTaskRow(
      id: id.present ? id.value : row.id,
      planId: planId.present ? planId.value : row.planId,
      dayIndex: dayIndex.present ? dayIndex.value : row.dayIndex,
      date: date.present ? date.value : row.date,
      workoutJson: workoutJson.present ? workoutJson.value : row.workoutJson,
      mealsJson: mealsJson.present ? mealsJson.value : row.mealsJson,
      completedWorkout:
          completedWorkout.present ? completedWorkout.value : row.completedWorkout,
      completedMeals:
          completedMeals.present ? completedMeals.value : row.completedMeals,
      xpAwarded: xpAwarded.present ? xpAwarded.value : row.xpAwarded,
      completedAt: completedAt.present ? completedAt.value : row.completedAt,
    );
  }
}

class ChatMessageRow extends DataClass implements Insertable<ChatMessageRow> {
  final int id;
  final int planId;
  final String role;
  final String content;
  final DateTime createdAt;

  const ChatMessageRow({
    required this.id,
    required this.planId,
    required this.role,
    required this.content,
    required this.createdAt,
  });

  factory ChatMessageRow.fromData(Map<String, dynamic> data) => ChatMessageRow(
        id: data['id'] as int,
        planId: data['plan_id'] as int,
        role: data['role'] as String,
        content: data['content'] as String,
        createdAt: data['created_at'] as DateTime,
      );

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['plan_id'] = Variable<int>(planId);
    map['role'] = Variable<String>(role);
    map['content'] = Variable<String>(content);
    map['created_at'] = Variable<DateTime>(createdAt);
    return map;
  }

  ChatMessageRow copyWith({
    int? id,
    int? planId,
    String? role,
    String? content,
    DateTime? createdAt,
  }) =>
      ChatMessageRow(
        id: id ?? this.id,
        planId: planId ?? this.planId,
        role: role ?? this.role,
        content: content ?? this.content,
        createdAt: createdAt ?? this.createdAt,
      );

  @override
  String toString() => 'ChatMessageRow(id: $id, role: $role)';
}

class ChatMessagesCompanion extends UpdateCompanion<ChatMessageRow> {
  final Value<int> id;
  final Value<int> planId;
  final Value<String> role;
  final Value<String> content;
  final Value<DateTime> createdAt;

  const ChatMessagesCompanion({
    this.id = const Value.absent(),
    this.planId = const Value.absent(),
    this.role = const Value.absent(),
    this.content = const Value.absent(),
    this.createdAt = const Value.absent(),
  });

  ChatMessagesCompanion.insert({
    this.id = const Value.absent(),
    required int planId,
    required String role,
    required String content,
    required DateTime createdAt,
  })  : planId = Value(planId),
        role = Value(role),
        content = Value(content),
        createdAt = Value(createdAt);

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) map['id'] = Variable<int>(id.value);
    if (planId.present) map['plan_id'] = Variable<int>(planId.value);
    if (role.present) map['role'] = Variable<String>(role.value);
    if (content.present) map['content'] = Variable<String>(content.value);
    if (createdAt.present) {
      map['created_at'] = Variable<DateTime>(createdAt.value);
    }
    return map;
  }

  @override
  ChatMessageRow attachRow(ChatMessageRow row) {
    return ChatMessageRow(
      id: id.present ? id.value : row.id,
      planId: planId.present ? planId.value : row.planId,
      role: role.present ? role.value : row.role,
      content: content.present ? content.value : row.content,
      createdAt: createdAt.present ? createdAt.value : row.createdAt,
    );
  }
}

class Streak extends DataClass implements Insertable<Streak> {
  final int id;
  final int currentDays;
  final int longestDays;
  final DateTime? lastActiveDate;
  final int freezesRemaining;

  const Streak({
    required this.id,
    required this.currentDays,
    required this.longestDays,
    this.lastActiveDate,
    required this.freezesRemaining,
  });

  factory Streak.fromData(Map<String, dynamic> data) => Streak(
        id: data['id'] as int,
        currentDays: data['current_days'] as int,
        longestDays: data['longest_days'] as int,
        lastActiveDate: data['last_active_date'] as DateTime?,
        freezesRemaining: data['freezes_remaining'] as int,
      );

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['current_days'] = Variable<int>(currentDays);
    map['longest_days'] = Variable<int>(longestDays);
    if (!nullToAbsent || lastActiveDate != null) {
      map['last_active_date'] = Variable<DateTime?>(lastActiveDate);
    }
    map['freezes_remaining'] = Variable<int>(freezesRemaining);
    return map;
  }

  Streak copyWith({
    int? id,
    int? currentDays,
    int? longestDays,
    Value<DateTime?> lastActiveDate = const Value.absent(),
    int? freezesRemaining,
  }) =>
      Streak(
        id: id ?? this.id,
        currentDays: currentDays ?? this.currentDays,
        longestDays: longestDays ?? this.longestDays,
        lastActiveDate:
            lastActiveDate.present ? lastActiveDate.value : this.lastActiveDate,
        freezesRemaining: freezesRemaining ?? this.freezesRemaining,
      );

  @override
  String toString() => 'Streak(id: $id, currentDays: $currentDays)';
}

class StreaksCompanion extends UpdateCompanion<Streak> {
  final Value<int> id;
  final Value<int> currentDays;
  final Value<int> longestDays;
  final Value<DateTime?> lastActiveDate;
  final Value<int> freezesRemaining;

  const StreaksCompanion({
    this.id = const Value.absent(),
    this.currentDays = const Value.absent(),
    this.longestDays = const Value.absent(),
    this.lastActiveDate = const Value.absent(),
    this.freezesRemaining = const Value.absent(),
  });

  StreaksCompanion.insert({
    this.id = const Value.absent(),
    this.currentDays = const Value.absent(),
    this.longestDays = const Value.absent(),
    this.lastActiveDate = const Value.absent(),
    this.freezesRemaining = const Value.absent(),
  })  : currentDays = const Value(0),
        longestDays = const Value(0),
        freezesRemaining = const Value(2);

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) map['id'] = Variable<int>(id.value);
    if (currentDays.present) {
      map['current_days'] = Variable<int>(currentDays.value);
    }
    if (longestDays.present) map['longest_days'] = Variable<int>(longestDays.value);
    if (lastActiveDate.present) {
      map['last_active_date'] = Variable<DateTime?>(lastActiveDate.value);
    }
    if (freezesRemaining.present) {
      map['freezes_remaining'] = Variable<int>(freezesRemaining.value);
    }
    return map;
  }

  @override
  Streak attachRow(Streak row) {
    return Streak(
      id: id.present ? id.value : row.id,
      currentDays: currentDays.present ? currentDays.value : row.currentDays,
      longestDays: longestDays.present ? longestDays.value : row.longestDays,
      lastActiveDate:
          lastActiveDate.present ? lastActiveDate.value : row.lastActiveDate,
      freezesRemaining:
          freezesRemaining.present ? freezesRemaining.value : row.freezesRemaining,
    );
  }
}

class GamificationEvent extends DataClass implements Insertable<GamificationEvent> {
  final int id;
  final String eventType;
  final int value;
  final DateTime createdAt;

  const GamificationEvent({
    required this.id,
    required this.eventType,
    required this.value,
    required this.createdAt,
  });

  factory GamificationEvent.fromData(Map<String, dynamic> data) =>
      GamificationEvent(
        id: data['id'] as int,
        eventType: data['event_type'] as String,
        value: data['value'] as int,
        createdAt: data['created_at'] as DateTime,
      );

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['event_type'] = Variable<String>(eventType);
    map['value'] = Variable<int>(value);
    map['created_at'] = Variable<DateTime>(createdAt);
    return map;
  }

  GamificationEvent copyWith({
    int? id,
    String? eventType,
    int? value,
    DateTime? createdAt,
  }) =>
      GamificationEvent(
        id: id ?? this.id,
        eventType: eventType ?? this.eventType,
        value: value ?? this.value,
        createdAt: createdAt ?? this.createdAt,
      );

  @override
  String toString() => 'GamificationEvent(id: $id, eventType: $eventType)';
}

class GamificationEventsCompanion extends UpdateCompanion<GamificationEvent> {
  final Value<int> id;
  final Value<String> eventType;
  final Value<int> value;
  final Value<DateTime> createdAt;

  const GamificationEventsCompanion({
    this.id = const Value.absent(),
    this.eventType = const Value.absent(),
    this.value = const Value.absent(),
    this.createdAt = const Value.absent(),
  });

  GamificationEventsCompanion.insert({
    this.id = const Value.absent(),
    required String eventType,
    required int value,
    required DateTime createdAt,
  })  : eventType = Value(eventType),
        value = Value(value),
        createdAt = Value(createdAt);

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) map['id'] = Variable<int>(id.value);
    if (eventType.present) map['event_type'] = Variable<String>(eventType.value);
    if (value.present) map['value'] = Variable<int>(value.value);
    if (createdAt.present) {
      map['created_at'] = Variable<DateTime>(createdAt.value);
    }
    return map;
  }

  @override
  GamificationEvent attachRow(GamificationEvent row) {
    return GamificationEvent(
      id: id.present ? id.value : row.id,
      eventType: eventType.present ? eventType.value : row.eventType,
      value: value.present ? value.value : row.value,
      createdAt: createdAt.present ? createdAt.value : row.createdAt,
    );
  }
}

class Badge extends DataClass implements Insertable<Badge> {
  final String code;
  final String name;
  final String description;
  final String icon;
  final String conditionJson;

  const Badge({
    required this.code,
    required this.name,
    required this.description,
    required this.icon,
    required this.conditionJson,
  });

  factory Badge.fromData(Map<String, dynamic> data) => Badge(
        code: data['code'] as String,
        name: data['name'] as String,
        description: data['description'] as String,
        icon: data['icon'] as String,
        conditionJson: data['condition_json'] as String,
      );

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['code'] = Variable<String>(code);
    map['name'] = Variable<String>(name);
    map['description'] = Variable<String>(description);
    map['icon'] = Variable<String>(icon);
    map['condition_json'] = Variable<String>(conditionJson);
    return map;
  }

  Badge copyWith({
    String? code,
    String? name,
    String? description,
    String? icon,
    String? conditionJson,
  }) =>
      Badge(
        code: code ?? this.code,
        name: name ?? this.name,
        description: description ?? this.description,
        icon: icon ?? this.icon,
        conditionJson: conditionJson ?? this.conditionJson,
      );

  @override
  String toString() => 'Badge(code: $code, name: $name)';
}

class BadgesCompanion extends UpdateCompanion<Badge> {
  final Value<String> code;
  final Value<String> name;
  final Value<String> description;
  final Value<String> icon;
  final Value<String> conditionJson;

  const BadgesCompanion({
    this.code = const Value.absent(),
    this.name = const Value.absent(),
    this.description = const Value.absent(),
    this.icon = const Value.absent(),
    this.conditionJson = const Value.absent(),
  });

  BadgesCompanion.insert({
    required String code,
    required String name,
    required String description,
    required String icon,
    required String conditionJson,
  })  : code = Value(code),
        name = Value(name),
        description = Value(description),
        icon = Value(icon),
        conditionJson = Value(conditionJson);

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (code.present) map['code'] = Variable<String>(code.value);
    if (name.present) map['name'] = Variable<String>(name.value);
    if (description.present) {
      map['description'] = Variable<String>(description.value);
    }
    if (icon.present) map['icon'] = Variable<String>(icon.value);
    if (conditionJson.present) {
      map['condition_json'] = Variable<String>(conditionJson.value);
    }
    return map;
  }

  @override
  Badge attachRow(Badge row) {
    return Badge(
      code: code.present ? code.value : row.code,
      name: name.present ? name.value : row.name,
      description: description.present ? description.value : row.description,
      icon: icon.present ? icon.value : row.icon,
      conditionJson:
          conditionJson.present ? conditionJson.value : row.conditionJson,
    );
  }
}

// Table-info accessors: `db.userProfiles`, `db.plans`, ... — see the note
// in `_$AppDatabase` above. They live as fields on `_$AppDatabase` once
// build_runner has run.
